export const BROWSER_ARGS = ['--disable-features=IsolateOrigins',
    '--disable-site-isolation-trials',
    '--autoplay-policy=user-gesture-required',
    '--disable-background-networking',
    '--disable-background-timer-throttling',
    '--disable-backgrounding-occluded-windows',
    '--disable-breakpad',
    '--disable-client-side-phishing-detection',
    '--disable-component-update',
    '--disable-default-apps',
    '--disable-dev-shm-usage',
    '--disable-domain-reliability',
    '--disable-extensions',
    '--disable-features=AudioServiceOutOfProcess',
    '--disable-hang-monitor',
    '--disable-ipc-flooding-protection',
    '--disable-notifications',
    '--disable-offer-store-unmasked-wallet-cards',
    '--disable-popup-blocking',
    '--disable-print-preview',
    '--disable-prompt-on-repost',
    '--disable-renderer-backgrounding',
    '--disable-setuid-sandbox',
    '--disable-speech-api',
    '--disable-sync',
    '--hide-scrollbars',
    '--ignore-gpu-blacklist',
    '--metrics-recording-only',
    '--mute-audio',
    '--no-default-browser-check',
    '--no-first-run',
    '--no-pings',
    '--no-sandbox',
    '--no-zygote',
    '--password-store=basic',
    '--use-gl=swiftshader',
    '--use-mock-keychain']

export const SALESFORCE_API_KEY = "M01WRzk4R3EyTzhQbzRabHdFVXhSZkJrbDJtWFpwTzVIWFV5ajZHT0wwbERudlM1WGVYb1FvX0RwVXc5LnNSX21ycXdjd2xnUnRoc09reTVpNWhnVzozM0E1QThFNTcyODU0QkVGNDMzMDM5QURBQUI1MDk0NEIxMEU5NDE5RTNCN0MyMDg0MUM1OTE1OTZENEM0MDI0"
export const SALESFORCE_URL_BASE = "https://mertus2-dev-ed.develop.my.salesforce.com";
export const SALESFORCE_OWNER_ID = "0057R00000CyyrXQAR";
export const PATH_RESUME = 'resume.pdf'
export const PATH_FOOTER = 'footer.jpeg'
